# Generated by Django 2.2.7 on 2019-11-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerclass',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
