# Generated by Django 2.2.7 on 2019-11-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('EmpId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('EmpName', models.CharField(max_length=50)),
                ('EmpPassword', models.CharField(max_length=50)),
                ('EmpPh', models.CharField(max_length=15)),
                ('EmpCategory', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('IngrName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('IngrAmt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('ItemId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ItemCategory', models.CharField(max_length=50)),
                ('ItemName', models.CharField(max_length=20)),
                ('ItemPrice', models.IntegerField()),
                ('EmpId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employeeapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='itemRequires',
            fields=[
                ('ItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employeeapp.items')),
                ('ItemQty', models.IntegerField()),
                ('IngrName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapp.ingredients')),
            ],
        ),
    ]
