# Generated by Django 2.2.7 on 2019-11-27 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='itemRequires',
        ),
    ]
