# Generated by Django 2.2.7 on 2019-11-27 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_delete_itemrequires'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemRequires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemQty', models.IntegerField()),
                ('IngrName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapp.ingredients')),
                ('ItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapp.items')),
            ],
        ),
    ]
