# Generated by Django 2.2.7 on 2019-11-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_itemrequires'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='ItemDesc',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
