# Generated by Django 2.2.7 on 2019-11-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.IntegerField()),
                ('ItemId', models.IntegerField()),
                ('ItemQty', models.IntegerField()),
            ],
        ),
    ]
