# Generated by Django 2.2.7 on 2019-11-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
