# Generated by Django 2.2.7 on 2019-11-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeeapp', '0004_items_itemdesc'),
        ('ordersapp', '0002_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('PayId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('PayMode', models.CharField(max_length=50)),
                ('PayAmt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.IntegerField()),
                ('ItemQty', models.IntegerField()),
                ('ItemId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employeeapp.items')),
            ],
        ),
    ]
