# Generated by Django 2.2.7 on 2019-11-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('SupId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SupName', models.CharField(max_length=50)),
                ('SupPassword', models.CharField(max_length=50)),
                ('SupPh', models.CharField(max_length=15)),
                ('EmpId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employeeapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Ssupplies',
            fields=[
                ('SupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='supplierapp.supplier')),
                ('IngrName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapp.ingredients')),
            ],
        ),
    ]
